name: Deploy UI
on:
  push:
    branches:    
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install
    - run: yarn build
    - name: Publish
      uses: cloudflare/wrangler-action@1.2.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        IS_WORKER: true
